### ISSUE TITLE
some komodo_...() functions needs to be wrapped by cs_main lock

### ISSUE THREAD

**Issue by dimxy** [KomodoPlatform/komodo#482]
Several functions komodo_chainactive komodo_heightstamp komodo_chainactive_timestamp access the chainActive object that needs to be protected by cs_main critical section.
It looks like calls to these functions are not surrounded with LOC(cs_main) when required. At least the nspv server part implementation may call those functions without cs_main lock.
That needs to be added.
Also it is suggested to add AssertLockHeld(cs_main) into those functions to track locks (this is activated by macro DEBUG_LOCKORDER)

**Comment by jmjatlanta** [comment]
An option to consider: move the functionality of those methods to within the CChain class and do the locking there. Sometimes this can centralize the mutex to only be needed within the class, easing maintenance, and removing the need for the assertion.

**Comment by dimxy** [comment]
> The long answer is to rework the purpose of cs_main (i.e. make it responsible for less) before performance takes a hit
probably we could think of using the shared lock on reading and exclusive lock on writing. Wondering why this was not done in the original code

**Comment by jmjatlanta** [comment]
> Wondering why this was not done in the original code

If we could move to C++17 (preferred IMO, just not sure clients would agree), read/write locks are part of the standard. If not, such things have been available in boost since 1.35.

As I am sure you are aware, such mechanisms carry overhead. But for lock contention issues (which can often be the case for frequent reads and occasional writes), there is sometimes a performance gain. I would imagine we do a lot more reading than writing to things like the block index, so I'd say your idea is a good one at least in some areas.

With so many references to `cs_main` in the code, I suspect that locking mechanism is either
1. Attempting to protect too much, in which case we need more granular control (more mutexes).   or
2. Locking is done too high up in the software stack, and should be moved further down.   or
3. A combination of the two points above. <- my guess     or
4. What we have now is the best way to do it, and we need to document it with reasons why.    <- possible, but not probable

**Comment by TheComputerGenie** [comment]
> Wondering why this was not done in the original code

afaik, locks have only ever historically been used "sparingly" and added as necessity dictated rather than as a matter of style and practice

**Comment by dimxy** [comment]
yes, however komodo introduced a NSPV protocol which implies many client connections to nspv nodes doing multiple read requests (in comparison to ordinary nodes) so we should think of adjusting the locking strategy

**Comment by TheComputerGenie** [comment]
While I do think it's something to look at, my main point was to answer the "question" of "why".
That being said, I do urge caution so as to not over-do it and add locks in places that may work in situationX but cause situationY to fail or crash. The hardest part of changing calls (in komodo more specifically than any other daemon I can think of) is the complexity of situations that arise from it having no less than 5 different use function models: LabsNN, NN, "normal client", some obscure params choices, etc. (some of which get over looked in using/testing it for one or two specific things).

**Comment by dimxy** [comment]
many missing locks were added in #559
